/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.ManipulaDBC;
import bd.Querys;
import bd.sqlConsultas;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edwin
 */
public class Modificaciones extends javax.swing.JFrame {
    Connection con;
    int xy, xx;
    public ArrayList<Object> columnaMap1 = new ArrayList();
     sqlConsultas consult= new sqlConsultas();
     
    /**
     * Creates new form Modificaciones
     */
    public Modificaciones() {
        initComponents();
        ((JTextField) this.calendario.getDateEditor()).setEditable(false);  
        popupmenu();
    }
    public void popupmenu(){
    JPopupMenu popupMenu = new JPopupMenu();
    JMenuItem menuItemAdd = new JMenuItem("Modificar");
    menuItemAdd.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
           
            
            Querys q = new Querys();
            
            if (jTable1.getSelectedColumn()==1) {
                String columnas = "cantidad";
            
            String values =
            "'" + jTable1.getValueAt(jTable1.getSelectedRow(), jTable1.getSelectedColumn()).toString()+"'";
            q.Modificar(con, "productoventa",columnas, values, "idventa = " + idventaPtxt.getText() +" AND "+ "idproducto = "+jTable1.getValueAt(jTable1.getSelectedRow(), 0));          
            }else if (jTable1.getSelectedColumn()==2) {
               String columnas = "subtotal";
            
            String values = 
            "'" + jTable1.getValueAt(jTable1.getSelectedRow(), jTable1.getSelectedColumn()).toString()+"'";
            q.Modificar(con, "productoventa",columnas, values, "idventa = " + idventaPtxt.getText() +" AND "+ "idproducto = "+jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());  
            }

            
           
       
        }
    });
    popupMenu.add(menuItemAdd);
    jTable1.setComponentPopupMenu(popupMenu);
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        idVentatxt = new javax.swing.JTextField();
        btnMostrarV = new javax.swing.JButton();
        fechatxt = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JDateChooser();
        fechatxt1 = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();
        btnModV = new javax.swing.JButton();
        btnLimpiarV = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        idventaPtxt = new javax.swing.JTextField();
        btnMostrarVP = new javax.swing.JButton();
        btnLimpiarVP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLMinimizar = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(532, 471));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("ID del venta:");

        idVentatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idVentatxtActionPerformed(evt);
            }
        });
        idVentatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idVentatxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idVentatxtKeyTyped(evt);
            }
        });

        btnMostrarV.setText("Mostrar producto");
        btnMostrarV.setEnabled(false);
        btnMostrarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVActionPerformed(evt);
            }
        });
        btnMostrarV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMostrarVKeyPressed(evt);
            }
        });

        fechatxt.setText("Fecha");

        calendario.setDateFormatString("yyyy-MM-dd");
        calendario.setEnabled(false);
        calendario.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                calendarioInputMethodTextChanged(evt);
            }
        });
        calendario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calendarioKeyPressed(evt);
            }
        });

        fechatxt1.setText("Total");

        totaltxt.setEnabled(false);

        btnModV.setText("Modificar");
        btnModV.setEnabled(false);
        btnModV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModVActionPerformed(evt);
            }
        });
        btnModV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnModVKeyPressed(evt);
            }
        });

        btnLimpiarV.setText("Limpiar");
        btnLimpiarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(fechatxt)
                            .addComponent(fechatxt1))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idVentatxt)
                            .addComponent(totaltxt)
                            .addComponent(calendario, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMostrarV)
                        .addGap(68, 68, 68)
                        .addComponent(btnLimpiarV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(btnModV)
                        .addGap(103, 103, 103))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idVentatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMostrarV)
                        .addComponent(btnModV))
                    .addComponent(btnLimpiarV))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechatxt)
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechatxt1)
                    .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Venta", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("ID venta:");

        idventaPtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idventaPtxtKeyPressed(evt);
            }
        });

        btnMostrarVP.setText("Mostrar producto-venta");
        btnMostrarVP.setEnabled(false);
        btnMostrarVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVPActionPerformed(evt);
            }
        });
        btnMostrarVP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMostrarVPKeyPressed(evt);
            }
        });

        btnLimpiarVP.setText("Limpiar");
        btnLimpiarVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarVPActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "idproducto", "cantidad", "subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idventaPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnMostrarVP)
                                .addGap(59, 59, 59)
                                .addComponent(btnLimpiarVP)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idventaPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarVP)
                    .addComponent(btnLimpiarVP))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ProductoVenta", jPanel3);

        jLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize1.png"))); // NOI18N
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMinimizarMouseClicked(evt);
            }
        });

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(jLMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCerrar))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMouseClicked

    private void idVentatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idVentatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idVentatxtActionPerformed

    private void btnMostrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVActionPerformed
        this.setCursor(WAIT_CURSOR);

        Querys q = new Querys();
        boolean flag = false;
        try {
            columnaMap1 = q.Seleccion(con, "idventa", "venta", "", false);
        } catch (Exception e) {
            System.out.println("Error en el SELECT...exception ->" + e);
        }

        for (int i = 0; i < columnaMap1.size(); i++) {
            if (columnaMap1.get(i).toString().trim().equals( idVentatxt.getText())) {
                flag = false;
                break;
            } else {
                flag = true;
            }
        }
        if (flag) {
            Mensaje.error(this, "El ID que intenta buscar no existe\n"
                + "Intente ingresar un ID valido");
            CtrlInterfaz.selecciona(idVentatxt);
        } else {
            try {
                columnaMap1 = q.Seleccion(con, "*", "venta", "idventa = " + idVentatxt.getText(), false);
            } catch (Exception e) {
                System.out.println("Error en el INSERT...exception ->" + e);
            }
            SimpleDateFormat fecha = new SimpleDateFormat("yyyy-MM-dd");
            Date fechat ;
            try {
                fechat = fecha.parse(columnaMap1.get(1).toString().trim());
                calendario.setDate(fechat);
            } catch (ParseException ex) {
                Logger.getLogger(Modificaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            totaltxt.setText(columnaMap1.get(2).toString().trim());
            
            CtrlInterfaz.habilita(true, btnModV);
            flag = false;
        }

        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_btnMostrarVActionPerformed

    private void btnMostrarVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMostrarVKeyPressed
        if (evt.getKeyChar() == '\n') {
            btnMostrarVActionPerformed(null);
           ((JTextField) this.calendario.getDateEditor()).setEditable(true); 
          calendario.getCalendarButton().setEnabled(true);
           Validaciones.enter(this, evt, totaltxt);
        }
    }//GEN-LAST:event_btnMostrarVKeyPressed

    private void btnModVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModVActionPerformed

        if (Mensaje.pregunta(this, "¿Esta seguro de que desea modificar el siguiente registro?") == JOptionPane.YES_OPTION) {
            Querys q = new Querys();
            String columnas = "idventa,fecha,total";
            String values = "'" + idVentatxt.getText() + "'," 
            + "'" + ((JTextField) this.calendario.getDateEditor()).getText() + "',"
            + "'" + totaltxt.getText()+"'";

            try {
                q.Modificar(con, "venta",columnas, values, "idventa = " + idVentatxt.getText());
            } catch (Exception e) {
                System.out.println("Error en el UPDATE...exception ->" + e);
            }

            Mensaje.exito(this, "Se ha alterado el registro con exito");
        }else{
            Mensaje.error(this, "No se ha modificado el registro");
        }
        btnLimpiarVActionPerformed(evt);
    }//GEN-LAST:event_btnModVActionPerformed

    private void btnModVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnModVKeyPressed
        if (evt.getKeyChar() == '\n'){
            btnModVActionPerformed(null);
        }
    }//GEN-LAST:event_btnModVKeyPressed

    private void btnLimpiarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarVActionPerformed
        CtrlInterfaz.limpia(idVentatxt,((JTextField) this.calendario.getDateEditor()), totaltxt);
        
        CtrlInterfaz.habilita(false, btnMostrarV, btnModV,((JTextField) this.calendario.getDateEditor()), totaltxt);
        CtrlInterfaz.selecciona(idVentatxt);
    }//GEN-LAST:event_btnLimpiarVActionPerformed

    private void idVentatxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idVentatxtKeyPressed
       Validaciones.enterEntero(this, evt, idVentatxt, btnMostrarV);
    }//GEN-LAST:event_idVentatxtKeyPressed

    private void idVentatxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idVentatxtKeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_idVentatxtKeyTyped

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        con = ManipulaDBC.conectaDB();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ManipulaDBC.desconectaDB(con);
    }//GEN-LAST:event_formWindowClosed

    private void calendarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calendarioKeyPressed
        // TODO add your handling code here:
        
            
        
    }//GEN-LAST:event_calendarioKeyPressed

    private void calendarioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_calendarioInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarioInputMethodTextChanged

    private void btnMostrarVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVPActionPerformed
        String campos= "idproducto, cantidad, subtotal";
        String bd= "productoventa";
        String condicion= "idventa= "+idventaPtxt.getText();
        consult.visualizar_tabla5(jTable1,condicion,campos, bd);
    }//GEN-LAST:event_btnMostrarVPActionPerformed

    private void btnMostrarVPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMostrarVPKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarVPKeyPressed

    private void btnLimpiarVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarVPActionPerformed
         CtrlInterfaz.limpia(idventaPtxt);
        
        CtrlInterfaz.selecciona(idventaPtxt);
       DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        tb.removeRow(tb.getRowCount()-1);
        }
        
    }//GEN-LAST:event_btnLimpiarVPActionPerformed

    private void idventaPtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idventaPtxtKeyPressed
        Validaciones.enterEntero(this, evt, idventaPtxt, btnMostrarVP);
    }//GEN-LAST:event_idventaPtxtKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiarV;
    private javax.swing.JButton btnLimpiarVP;
    private javax.swing.JButton btnModV;
    private javax.swing.JButton btnMostrarV;
    private javax.swing.JButton btnMostrarVP;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JLabel fechatxt;
    private javax.swing.JLabel fechatxt1;
    private javax.swing.JTextField idVentatxt;
    private javax.swing.JTextField idventaPtxt;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables
}
