/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.ManipulaDBC;
import bd.Querys;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class ventaProductos extends javax.swing.JFrame {

    Connection con;
    ArrayList<Object> columnaMap1 = new ArrayList();
    ArrayList<Object> columnaMap3 = new ArrayList();
    
    float precioTotal = 0;

    /**
     * Creates new form altasProduct
     */
    public ventaProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTFProductID = new javax.swing.JTextField();
        jTFCantID = new javax.swing.JTextField();
        jTFSubtotal = new javax.swing.JTextField();
        jBVender = new javax.swing.JButton();
        jLTitulo = new javax.swing.JLabel();
        jLNamePro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFVentaID = new javax.swing.JTextField();
        jBLimpia = new javax.swing.JButton();
        jLMinimizar = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVentas = new javax.swing.JTable();
        jBAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFProductID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFProductIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFProductIDKeyTyped(evt);
            }
        });
        jPanel1.add(jTFProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 180, -1));

        jTFCantID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCantIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCantIDKeyTyped(evt);
            }
        });
        jPanel1.add(jTFCantID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 180, -1));

        jTFSubtotal.setEnabled(false);
        jPanel1.add(jTFSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 180, -1));

        jBVender.setText("Vender");
        jBVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVenderActionPerformed(evt);
            }
        });
        jPanel1.add(jBVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        jLTitulo.setText("Venta de productos");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLNamePro.setText("Id de venta:");
        jPanel1.add(jLNamePro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel1.setText("Id del producto:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setText("Cantidad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setText("Subtotal:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jTFVentaID.setEnabled(false);
        jPanel1.add(jTFVentaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 180, -1));

        jBLimpia.setText("Limpiar");
        jBLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiaActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jLMinimizar.setText("Minimizar");
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(jLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLCerrar.setText("Cerrar");
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jTVentas.setAutoCreateRowSorter(true);
        jTVentas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTVentas.setGridColor(new java.awt.Color(255, 255, 255));
        jTVentas.setSelectionBackground(new java.awt.Color(223, 227, 238));
        jTVentas.setSelectionForeground(new java.awt.Color(139, 157, 195));
        jTVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVentasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTVentasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 380, 130));

        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(jBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        con = ManipulaDBC.conectaDB();
        Querys q = new Querys();
        int ID;
        try {
            columnaMap1 = q.Seleccion(con, "idventa", "venta", "", false);
        } catch (Exception e) {
            System.out.println("Error en el SELECT de inicio 1...exception ->" + e);
        }

        if (columnaMap1.get(0).equals(" ")) {
            jTFVentaID.setText("1");
        } else {
            try {
                columnaMap1 = q.Seleccion(con, "MAX(idventa)", "venta", "", false);
                ID = Integer.parseInt((String) columnaMap1.get(0)) + 1;
                jTFVentaID.setText(String.valueOf(ID));
            } catch (Exception e) {
                System.out.println("Error en el SELECT de inicio 2...exception ->" + e);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ManipulaDBC.desconectaDB(con);
    }//GEN-LAST:event_formWindowClosed

    private void jBLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiaActionPerformed
        CtrlInterfaz.limpia(jTFProductID, jTFCantID);
        CtrlInterfaz.selecciona(jTFProductID);
    }//GEN-LAST:event_jBLimpiaActionPerformed

    private void jLMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMouseClicked

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        this.dispose();
        new menuPrincipal().setVisible(true);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jTVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVentasMouseClicked

    }//GEN-LAST:event_jTVentasMouseClicked

    private void jTVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVentasMousePressed

    }//GEN-LAST:event_jTVentasMousePressed

    private void jTFProductIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFProductIDKeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_jTFProductIDKeyTyped

    private void jTFProductIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFProductIDKeyPressed
        Validaciones.enterEntero(this, evt, jTFProductID, jTFCantID);
    }//GEN-LAST:event_jTFProductIDKeyPressed

    private void jTFCantIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCantIDKeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_jTFCantIDKeyTyped

    private void jTFCantIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCantIDKeyPressed
        Validaciones.enterEntero(this, evt, jTFCantID, jBAgregar);
    }//GEN-LAST:event_jTFCantIDKeyPressed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        mostrar();
        jBLimpiaActionPerformed(null);
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVenderActionPerformed
        jBLimpiaActionPerformed(null);
        precioTotal = 0;
    }//GEN-LAST:event_jBVenderActionPerformed

    private void mostrar() {
        DefaultTableModel model = new DefaultTableModel();
        Querys q = new Querys();
        ArrayList<Object> columnaMap2 = new ArrayList();

        int flag = 0;
        float precioF = 0;
        try {
            columnaMap2 = q.Seleccion(con, "id, precioventaun", "producto", "id='" + jTFProductID.getText() + "'", true);

            precioF = Float.parseFloat(jTFCantID.getText()) * Float.parseFloat((String) columnaMap2.get(1));
            precioTotal += precioF;
            jTFSubtotal.setText(String.valueOf(precioTotal));
            
            columnaMap3.add(columnaMap2.get(0));
            columnaMap3.add(columnaMap2.get(1));
            columnaMap3.add(jTFCantID.getText());
            columnaMap3.add(precioF);
            System.out.println(columnaMap3.size());
            
            model.setColumnIdentifiers(new Object[]{
                "ID Producto", "Precio C/U", "Cantidad", "Precio Final"
            });
            while (flag != columnaMap3.size()) {
                model.addRow(new Object[]{
                    columnaMap3.get(flag),
                    columnaMap3.get(flag + 1),
                    columnaMap3.get(flag + 2),
                    columnaMap3.get(flag + 3)
                });
                flag = flag + 4;
            }

            jTVentas.setModel(model);
        } catch (Exception e) {
            System.out.println("error --> " + e);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBLimpia;
    private javax.swing.JButton jBVender;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLNamePro;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCantID;
    private javax.swing.JTextField jTFProductID;
    private javax.swing.JTextField jTFSubtotal;
    private javax.swing.JTextField jTFVentaID;
    private javax.swing.JTable jTVentas;
    // End of variables declaration//GEN-END:variables
}
